x = open("file2.txt")
print("File is Opend")
print(x.read())
x.write("DileepLee")
x.close()
print("File is Closed")

# Whenever we run this code it is giving to the error,Becaouse we use the Try,Except,Finally blocks in this topic.